[build]
  base = "landing-page"     # Netlify will cd into this folder BEFORE install/build
  command = "npm run build" # runs the Vite build inside landing-page
  publish = "dist"          # IMPORTANT: path is relative to base, so just "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional but recommended) lock Node version to avoid surprises
[build.environment]
  NODE_VERSION = "18"
